language: python
python:
#- "2.7"
- "3.6"
- "3.7"
- "3.8"
install:
- pip install Flask
- touch dbconfig.py
- ./setup.py develop
- pip install coveralls
- ./setup.py compile_catalog
script:
- nosetests
- for a in b2bdata/*result; do [ -e "$a" ] && diff --color=always "$a" "${a/-result/-expected}"; done
after_success:
- coveralls
