# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TRAVIS: 1 # Skip tests requiring data
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
    name: Python ${{ matrix.python-version }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt install libmagickwand-dev inkscape libyaml-dev
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            Flask
            coveralls
      - name: Install dependencies
        run: |
          ./setup.py develop
          ./setup.py compile_catalog
          touch dbconfig.py
      - name: Unit tests
        run: |
          coverage run --source som_opendata ./setup.py test
      - uses: actions/upload-artifact@master
        if: failure() && hashFiles('b2bdata/*result*')
        with:
          name: b2b-results
          path: |
            b2bdata/*result*

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit tests

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
